require("config.options")
require("config.keymaps")

require("plugins.pack")

-- Setup plugins after pack loads them
vim.schedule(function()
    require("config.harpoon")
    require("config.telescope")
    require("config.treesitter")
    require("config.lsp")
    require("config.cmp")
    require("config.comment")
    require("config.conform")
    require("config.lint")
    require("config.whitespace")
    require("config.autopairs")
    require("config.which-key")
    require("config.comment_string")
end)
