### Autostart
#
exec dbus-update-activation-environment --all

exec pipewire
exec pipewire-pulse
exec wireplumber
exec /home/brett/.config/sway/conf.d/.swayinitapp.sh

# Autostart Apps
# Left Monitor
assign [app_id="ghostty"] workspace number 1

# Right Monitor
assign [app_id="Alacritty"] workspace number 11
assign [app_id="falkon"] workspace number 12
assign [class="steam"] workspace number 13
