### inputs

input type:keyboard {
    xkb_options caps:escape
}

seat seat0 xcursor_theme WinSur-dark-cursors 28
seat seat0 hide_cursor 1500

exec_always {
    swaymsg "seat seat0 xcursor_theme WinSur-dark-cursors 28"
}

