### outputs

#both monitors
output * bg /home/brett/Pictures/Wallpapers/void.png fill

#viewSonic
output DP-3 resolution 1920x1080@75Hz position 0,0 scale 1.2
workspace 1 output DP-3
workspace 2 output DP-3
workspace 3 output DP-3
workspace 4 output DP-3
workspace 5 output DP-3
workspace 6 output DP-3
workspace 7 output DP-3
workspace 8 output DP-3
workspace 9 output DP-3
workspace 10 output DP-3

# ASUS
output DP-2 resolution 1920x1080@75Hz position 1600,0  scale 1.2
workspace 11 output DP-2
workspace 12 output DP-2
workspace 13 output DP-2
workspace 14 output DP-2
workspace 15 output DP-2
workspace 16 output DP-2
workspace 17 output DP-2
workspace 18 output DP-2
workspace 19 output DP-2
workspace 20 output DP-2
